### ISSUE TITLE
File Not Found Error: [Errno 2] 

### ISSUE THREAD

**Issue by liujz0617** [hanxixuana/flowrisk#2]
试着运行 给定的example ，报错

File Not Found Error: [Errno 2] File C:\ProgramData\Anaconda3\lib\site-packages\flowrisk-0.2.3-py3.7.egg\flowrisk\examples\data\CBIO_2018_11_22.csv does not exist

**Comment by hanxixuana** [comment]
hey please try again

i just updated it to support 3.8
